apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: hyunjun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hyunjun-aks-demo-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: MYSQL_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: REDIS_PASSWORD
        - name: KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: KAFKA_PASSWORD
        - name: FLASK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: FLASK_SECRET_KEY
        - name: OTLP_ENDPOINT
          value: "http://otel-collector:4317"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: hyunjun
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000 