apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: hyunjun
type: Opaque
data:
  FLASK_SECRET_KEY: "MzkzMmRhOTQ2ODI1ZDk5MThjZTRiMzYxMGZiZTg5ZGNmYTM3NWIwZjM0NTMzZTRiNDliNDFhNGI3Mjg4YjljZA=="  # 생성된 실제 base64 값
  MYSQL_PASSWORD: "aHl1bmp1bg=="  # hyunjun을 base64로 인코딩
  REDIS_PASSWORD: "dW5kSUp6RmlSaQ=="  # undIJzFiRi를 base64로 인코딩
  KAFKA_PASSWORD: "WVRtc2MxYW1abA==" 