apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
  namespace: hyunjun
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: db-init
        image: mysql:8.0
        command: ["/bin/bash", "-c"]
        args:
        - |
          echo "Waiting for MariaDB to be ready..."
          while ! mysql -h hyunjun-mariadb -u root -p$MYSQL_ROOT_PASSWORD -e "SELECT 1" >/dev/null 2>&1; do
            sleep 2
          done
          echo "MariaDB is ready. Creating user and database..."
          
          # 사용자 및 데이터베이스 생성
          mysql -h hyunjun-mariadb -u root -p$MYSQL_ROOT_PASSWORD << EOF
          CREATE DATABASE IF NOT EXISTS testdb;
          CREATE USER IF NOT EXISTS 'testuser'@'%' IDENTIFIED BY 'hyunjun';
          GRANT ALL PRIVILEGES ON testdb.* TO 'testuser'@'%';
          FLUSH PRIVILEGES;
          EOF
          
          echo "User and database created. Creating tables..."
          
          # 테이블 생성
          mysql -h hyunjun-mariadb -u testuser -p$MYSQL_PASSWORD testdb << EOF
          DROP TABLE IF EXISTS messages;
          DROP TABLE IF EXISTS users;
          
          CREATE TABLE users (
              id INT AUTO_INCREMENT PRIMARY KEY,
              username VARCHAR(255) UNIQUE NOT NULL,
              password VARCHAR(255) NOT NULL,
              created_at DATETIME DEFAULT CURRENT_TIMESTAMP
          );
          
          CREATE TABLE messages (
              id INT AUTO_INCREMENT PRIMARY KEY,
              message TEXT,
              created_at DATETIME,
              user_id VARCHAR(255)
          );
          EOF
          
          echo "Tables created successfully!"
          echo "Database initialization completed!"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hyunjun-mariadb
              key: mariadb-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: MYSQL_PASSWORD
