apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: hyunjun
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS testdb;
    USE testdb;

    DROP TABLE IF EXISTS messages;
    DROP TABLE IF EXISTS users;

    CREATE TABLE users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE messages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        message TEXT,
        created_at DATETIME,
        user_id VARCHAR(255)
    );

---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
  namespace: hyunjun
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: db-init
        image: mysql:8.0
        command: ["/bin/bash", "-c"]
        args:
        - |
          echo "Waiting for MariaDB to be ready..."
          while ! mysql -h hyunjun-mariadb -u root -p$MYSQL_PASSWORD -e "SELECT 1" >/dev/null 2>&1; do
            sleep 2
          done
          echo "MariaDB is ready. Running initialization script..."
          mysql -h hyunjun-mariadb -u root -p$MYSQL_PASSWORD < /scripts/init.sql
          echo "Database initialization completed!"
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: init-script
          mountPath: /scripts
      volumes:
      - name: init-script
        configMap:
          name: db-init-script
