apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: hyunjun
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      resource:
        attributes:
          - key: environment
            value: "production"
            action: upsert

    exporters:
      otlp:
        endpoint: "http://grafana.20.249.154.255.nip.io:4317"
        tls:
          insecure: true
      debug:
        verbosity: detailed

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [otlp, debug]
        metrics:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [otlp, debug]
        logs:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [otlp, debug]
