name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{secrets.AZURE_REGISTRY_SERVER}}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Backend image
        run: |
          docker build -t ${{secrets.AZURE_REGISTRY_SERVER}}/hyunjun-aks-demo-backend:${{ github.sha }} \
            -t ${{secrets.AZURE_REGISTRY_SERVER}}/hyunjun-aks-demo-backend:latest .
          docker push ${{secrets.AZURE_REGISTRY_SERVER}}/hyunjun-aks-demo-backend:${{ github.sha }}
          docker push ${{secrets.AZURE_REGISTRY_SERVER}}/hyunjun-aks-demo-backend:latest

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{secrets.AZURE_REGISTRY_SERVER}}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Frontend image
        run: |
          docker build -t ${{secrets.AZURE_REGISTRY_SERVER}}/hyunjun-aks-demo-frontend:${{ github.sha }} \
            -t ${{secrets.AZURE_REGISTRY_SERVER}}/hyunjun-aks-demo-frontend:latest .
          docker push ${{secrets.AZURE_REGISTRY_SERVER}}/hyunjun-aks-demo-frontend:${{ github.sha }}
          docker push ${{secrets.AZURE_REGISTRY_SERVER}}/hyunjun-aks-demo-frontend:latest






