name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{secrets.AZURE_REGISTRY_SERVER}}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image to ACR
        run: |
          docker build -t ${{secrets.AZURE_REGISTRY_SERVER}}/${{ secrets.AZURE_REGISTRY_REPO_NAME }}:${{ github.sha }} \
            -t ${{secrets.AZURE_REGISTRY_SERVER}}/${{ secrets.AZURE_REGISTRY_REPO_NAME }}:latest .
          docker push ${{secrets.AZURE_REGISTRY_SERVER}}/${{ secrets.AZURE_REGISTRY_REPO_NAME }}:${{ github.sha }}
          docker push ${{secrets.AZURE_REGISTRY_SERVER}}/${{ secrets.AZURE_REGISTRY_REPO_NAME }}:latest

  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{secrets.AZURE_REGISTRY_SERVER}}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image to ACR
        run: |
          docker build -t ${{secrets.AZURE_REGISTRY_SERVER}}/${{ secrets.AZURE_REGISTRY_REPO_NAME }}:${{ github.sha }} \
            -t ${{secrets.AZURE_REGISTRY_SERVER}}/${{ secrets.AZURE_REGISTRY_REPO_NAME }}:latest .
          docker push ${{secrets.AZURE_REGISTRY_SERVER}}/${{ secrets.AZURE_REGISTRY_REPO_NAME }}:${{ github.sha }}
          docker push ${{secrets.AZURE_REGISTRY_SERVER}}/${{ secrets.AZURE_REGISTRY_REPO_NAME }}:latest






